### ISSUE TITLE
vision_to_mavros: ERROR IN SCRIPT message if reset_counter > 255?

### ISSUE THREAD

**Issue by rmackay9** [thien94/vision_to_mavros#23]
We've had a report that if the reset_counter > 255 the user sees an, "ERROR IN SCRIPT" message.

Perhaps we need a check [here](https://github.com/thien94/vision_to_mavros/blob/master/scripts/t265_to_mavlink.py#L583) to ensure the number rolls back to 0 (or perhaps 1) if > 255.

This was apparently the error message displayed in the companion computer logs:
return MAVLink_message.pack(self, mav, 158, struct.pack('<Qffffff21fB', self.usec, self.x, self.y, self.z, self.roll, self.pitch, self.yaw, self.covariance[0], self.covariance[1], self.covariance[2], self.covariance[3], self.covariance[4], self.covariance[5], self.covariance[6], self.covariance[7], self.covariance[8], self.covariance[9], self.covariance[10], self.covariance[11], self.covariance[12], self.covariance[13], self.covariance[14], self.covariance[15], self.covariance[16], self.covariance[17], self.covariance[18], self.covariance[19], self.covariance[20], self.reset_counter), force_mavlink1=force_mavlink1)
struct.error: ubyte format requires 0 <= number <= 255

**Comment by thien94** [comment]
@rmackay9 This issue has been fixed in the latest commit. Let me know if there is any further problem.

**Comment by rmackay9** [comment]
@thien94, great, thanks!!
