### ISSUE TITLE
The "d4xx_to_mavlink.py" script executes but stops giving output "Alarm Clock" 

### ISSUE THREAD

**Issue by Captain299792458** [thien94/vision_to_mavros#57]
@thien94 
I am trying to run "d4xx_to_mavlink.py" with D435 camera, but the script is not giving me any expected output. The final output is:
```
INFO: Advanced mode is enabled
Alarm clock
```

I have tried putting print statements at various places in the code, where the problem is likely to happen, and I found that it is with loading the json object. 

to be exact: the print statement after this line is NOT getting executed:
`advnc_mode.load_json(json_text)`

Any help would be much appreciated!

**Comment by Shreyas-dotcom** [comment]
I'm receiving the same error.

**Comment by Captain299792458** [comment]
> I'm receiving the same error.

found any resolve for this ?

**Comment by PTHGroup** [comment]
@Captain299792458 
We received the same error, to overcome this we modify the timer value in the d4xx_to_mavlink.py to a higher value. Works most of the time.

`signal.settimer(signal.ITIMER_REAL, 30)` # 30 Second timer

We are looking into trying to refresh the USB interface prior to connecting to see If this stops this issue.

Regards

PTH Group
