### ISSUE TITLE
i want  tilt the t265 nose up，i fix the t265_tf_to_mavros.launch，but it doesn't work

### ISSUE THREAD

**Issue by binbinshare** [thien94/vision_to_mavros#8]
for example，Downfacing, USB port to the right with t265，i modify t265_tf_to_mavros.launch，
<param name="roll_cam"          value="0" />
    <param name="pitch_cam"         value="-1.5707963" />
    <param name="yaw_cam"           value="0" />
    <param name="gamma_world"       value="-1.5707963" />
but the data remain unchanged，Do i need to make any other changes.

**Comment by hoangthien94** [comment]
Hi, can you share your modified launch file to have a closer look?

**Comment by thien94** [comment]
I will close the issue for now. Feel free to re-open if you have any more comments.
